const:
  default-page-size: 20

file:
  directory: D:/2024-02/download/greengram_ver3

jwt:
  issuer: green@green.kr
  secret-key: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFightingD23sdfsdf23FDSADFSDFDass502RoomForJavaSprinass502RoomForJavaSprin

mybatis:
  configuration:
    map-underscore-to-camel-case: true #snake_case column명을 자동으로 camel_case형으로 변환
  mapper-locations: mappers/**/*.xml

spring:
  application:
    name: GreenGramVer2
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost/jpa
    username: root
    password: green502
  jackson:
    default-property-inclusion: non_null #응답 JSON을 만들 때 null인 속성은 제외한다.

  jpa:
    database: mysql
    hibernate:
      #ddl-auto: update #entity가 없으면 생성, 기존 존재하는 엔티티는 새롭게 추가하는 것만 반영
      ddl-auto: update #entity를 서버 기동때마다 drop 후 create 한다
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true #로그 찍을때마다 보기편하게 포맷팅
        order_updates: true #JPA Batch 작업
    show-sql: true #JPA가 만든 쿼리문 로그에 출력

  servlet:
    multipart:
      max-file-size: 15MB

springdoc:
  swagger-ui:
    default-model-expand-depth: 10
    display-request-duration: true
    groups-order: asc
    operations-sorter: method
    path: /swagger
    tags-sorter: alpha
  cache:
    disabled: true


